### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/sublime_text/Settings/orgmode-store.bin.gz'

### ISSUE THREAD

**Issue by lianghu** [danielmagnussons/orgmode#56]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "~/.config/sublime-text-3/Packages/orgmode/orgmode_store.py", line 41, in on_deactivated
    self.save(view, 'on_deactivated')
  File "~/.config/sublime-text-3/Packages/orgmode/orgmode_store.py", line 90, in save
    with GzipFile(self.store, 'wb') as f:
  File "./gzip.py", line 184, in **init**
FileNotFoundError: [Errno 2] No such file or directory: '/opt/sublime_text/Settings/orgmode-store.bin.gz'

**Comment by yoyosan** [comment]
To temporarily solve this just copy the file from `/home/user/.config/sublime-text-3/Packages/Settings/orgmode_store.bin.gz` into `/opt/sublime_text/Settings/orgmode-store.bin.gz`.
Also, give it permissions so that the user you're running Sublime with can access it.

That's all.

**Comment by danielmagnussons** [comment]
Hopefully this fixes it: fa487b1a493afcaabae4a640671b66170b814fb4
